# Generated by Django 5.2 on 2025-12-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(),
        ),
    ]
